// login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGIN_INITIAL_STATE = 'USER_LOGIN_INITIAL_STATE'

// forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SENT = 'FORGOT_PASSWORD_SENT'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'
export const FORGOT_PASSWORD_INITIAL = 'FORGOT_PASSWORD_INITIAL'

// token validation (ping/me)
export const VALIDATED_TOKEN = 'VALIDATED_TOKEN'
export const EXPIRED_TOKEN = 'EXPIRED_TOKEN'

// update password
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'
export const CHANGE_PASSWORD_INITIAL_STATE = 'CHANGE_PASSWORD_INITIAL_STATE'

// event list
export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST'
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS'
export const EVENT_LIST_FAILURE = 'EVENT_LIST_FAILURE'

// event summary 
export const EVENT_SUMMARY_REQUEST = 'EVENT_SUMMARY_REQUEST'
export const EVENT_SUMMARY_SUCCESS = 'EVENT_SUMMARY_SUCCESS'
export const EVENT_SUMMARY_FAILURE = 'EVENT_SUMMARY_FAILURE'

// event sales per date 
export const EVENT_SALES_PER_DATE_REQUEST = 'EVENT_SALES_PER_DATE_REQUEST'
export const EVENT_SALES_PER_DATE_SUCCESS = 'EVENT_SALES_PER_DATE_SUCCESS'
export const EVENT_SALES_PER_DATE_FAILURE = 'EVENT_SALES_PER_DATE_FAILURE'

// event sales per product 
export const EVENT_SALES_PER_PRODUCT_REQUEST = 'EVENT_SALES_PER_PRODUCT_REQUEST'
export const EVENT_SALES_PER_PRODUCT_SUCCESS = 'EVENT_SALES_PER_PRODUCT_SUCCESS'
export const EVENT_SALES_PER_PRODUCT_FAILURE = 'EVENT_SALES_PER_PRODUCT_FAILURE'

// find organizer by id
export const ORGANIZER_BY_ID_REQUEST = 'ORGANIZER_BY_ID_REQUEST'
export const ORGANIZER_BY_ID_SUCCESS = 'ORGANIZER_BY_ID_SUCCESS'
export const ORGANIZER_BY_ID_FAILURE = 'ORGANIZER_BY_ID_FAILURE'

// user Organizers
export const USER_ORGANIZERS_REQUEST = 'USER_ORGANIZERS_REQUEST'
export const USER_ORGANIZERS_SUCCESS = 'USER_ORGANIZERS_SUCCESS'
export const USER_ORGANIZERS_FAILURE = 'USER_ORGANIZERS_FAILURE'

// financial balance list
export const FINANCIAL_BALANCE_LIST_REQUEST = 'FINANCIAL_BALANCE_LIST_REQUEST'
export const FINANCIAL_BALANCE_LIST_SUCCESS = 'FINANCIAL_BALANCE_LIST_SUCCESS'
export const FINANCIAL_BALANCE_LIST_FAILURE = 'FINANCIAL_BALANCE_LIST_FAILURE'
